name: Continuous Integration
on: [pull_request]

jobs:
  ci:
    name: Quality & Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '7.4', '8.0', '8.1' ]
        symfony-version: [ '5.4.*', '6.*' ]
        composer-options: [ '', '--prefer-lowest' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - run: composer config extra.symfony.require "${{ matrix.symfony-version }}"
      - run: composer update -n --no-ansi ${{ matrix.composer-options }}
      - run: make quality test
